
PUT http://localhost:4000/patients/update/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "gender": "Male",
  "age": "45",
  "birthDate": "1985-06-15",
  "address": "987 New Address St, Springfield"
}
